---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-eventbridge-reader
  namespace: default
rules:
- apiGroups:
  - eventbridge.services.k8s.aws
  resources:
  - eventbuses
  verbs:
  - get
  - list
  - watch
