// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package rule

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	customPreCompare(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EventBusName, b.ko.Spec.EventBusName) {
		delta.Add("Spec.EventBusName", a.ko.Spec.EventBusName, b.ko.Spec.EventBusName)
	} else if a.ko.Spec.EventBusName != nil && b.ko.Spec.EventBusName != nil {
		if *a.ko.Spec.EventBusName != *b.ko.Spec.EventBusName {
			delta.Add("Spec.EventBusName", a.ko.Spec.EventBusName, b.ko.Spec.EventBusName)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.EventBusRef, b.ko.Spec.EventBusRef) {
		delta.Add("Spec.EventBusRef", a.ko.Spec.EventBusRef, b.ko.Spec.EventBusRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EventPattern, b.ko.Spec.EventPattern) {
		delta.Add("Spec.EventPattern", a.ko.Spec.EventPattern, b.ko.Spec.EventPattern)
	} else if a.ko.Spec.EventPattern != nil && b.ko.Spec.EventPattern != nil {
		if *a.ko.Spec.EventPattern != *b.ko.Spec.EventPattern {
			delta.Add("Spec.EventPattern", a.ko.Spec.EventPattern, b.ko.Spec.EventPattern)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression) {
		delta.Add("Spec.ScheduleExpression", a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression)
	} else if a.ko.Spec.ScheduleExpression != nil && b.ko.Spec.ScheduleExpression != nil {
		if *a.ko.Spec.ScheduleExpression != *b.ko.Spec.ScheduleExpression {
			delta.Add("Spec.ScheduleExpression", a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.State, b.ko.Spec.State) {
		delta.Add("Spec.State", a.ko.Spec.State, b.ko.Spec.State)
	} else if a.ko.Spec.State != nil && b.ko.Spec.State != nil {
		if *a.ko.Spec.State != *b.ko.Spec.State {
			delta.Add("Spec.State", a.ko.Spec.State, b.ko.Spec.State)
		}
	}

	return delta
}
