// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package rule

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/eventbridge"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/eventbridge/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/eventbridge-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Rule{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeRuleOutput
	resp, err = rm.sdkapi.DescribeRule(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeRule", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EventBusName != nil {
		ko.Spec.EventBusName = resp.EventBusName
	} else {
		ko.Spec.EventBusName = nil
	}
	if resp.EventPattern != nil {
		ko.Spec.EventPattern = resp.EventPattern
	} else {
		ko.Spec.EventPattern = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.ScheduleExpression != nil {
		ko.Spec.ScheduleExpression = resp.ScheduleExpression
	} else {
		ko.Spec.ScheduleExpression = nil
	}
	if resp.State != "" {
		ko.Spec.State = aws.String(string(resp.State))
	} else {
		ko.Spec.State = nil
	}

	rm.setStatusDefaults(ko)
	if err := rm.setResourceAdditionalFields(ctx, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeRuleInput, error) {
	res := &svcsdk.DescribeRuleInput{}

	if r.ko.Spec.EventBusName != nil {
		res.EventBusName = r.ko.Spec.EventBusName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	if err = validateRuleSpec(desired.ko.Spec); err != nil {
		return nil, ackerr.NewTerminalError(err)
	}

	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	unsetScheduleExpression(desired.ko.Spec, input)

	var resp *svcsdk.PutRuleOutput
	_ = resp
	resp, err = rm.sdkapi.PutRule(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutRule", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.RuleArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.RuleArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	if len(ko.Spec.Targets) > 0 {
		if err = rm.syncTargets(
			ctx,
			ko.Spec.Name, ko.Spec.EventBusName,
			ko.Spec.Targets, nil,
		); err != nil {
			return nil, err
		}
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutRuleInput, error) {
	res := &svcsdk.PutRuleInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EventBusName != nil {
		res.EventBusName = r.ko.Spec.EventBusName
	}
	if r.ko.Spec.EventPattern != nil {
		res.EventPattern = r.ko.Spec.EventPattern
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.ScheduleExpression != nil {
		res.ScheduleExpression = r.ko.Spec.ScheduleExpression
	}
	if r.ko.Spec.State != nil {
		res.State = svcsdktypes.RuleState(*r.ko.Spec.State)
	}
	if r.ko.Spec.Tags != nil {
		f7 := []svcsdktypes.Tag{}
		for _, f7iter := range r.ko.Spec.Tags {
			f7elem := &svcsdktypes.Tag{}
			if f7iter.Key != nil {
				f7elem.Key = f7iter.Key
			}
			if f7iter.Value != nil {
				f7elem.Value = f7iter.Value
			}
			f7 = append(f7, *f7elem)
		}
		res.Tags = f7
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if err = validateRuleSpec(desired.ko.Spec); err != nil {
		return nil, ackerr.NewTerminalError(err)
	}
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}
	if delta.DifferentAt("Spec.Targets") {
		if err = rm.syncTargets(
			ctx,
			desired.ko.Spec.Name, desired.ko.Spec.EventBusName,
			desired.ko.Spec.Targets, latest.ko.Spec.Targets,
		); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags", "Spec.Targets") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	unsetScheduleExpression(desired.ko.Spec, input)

	var resp *svcsdk.PutRuleOutput
	_ = resp
	resp, err = rm.sdkapi.PutRule(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutRule", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.RuleArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.RuleArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.PutRuleInput, error) {
	res := &svcsdk.PutRuleInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EventBusName != nil {
		res.EventBusName = r.ko.Spec.EventBusName
	}
	if r.ko.Spec.EventPattern != nil {
		res.EventPattern = r.ko.Spec.EventPattern
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.ScheduleExpression != nil {
		res.ScheduleExpression = r.ko.Spec.ScheduleExpression
	}
	if r.ko.Spec.State != nil {
		res.State = svcsdktypes.RuleState(*r.ko.Spec.State)
	}
	if r.ko.Spec.Tags != nil {
		f7 := []svcsdktypes.Tag{}
		for _, f7iter := range r.ko.Spec.Tags {
			f7elem := &svcsdktypes.Tag{}
			if f7iter.Key != nil {
				f7elem.Key = f7iter.Key
			}
			if f7iter.Value != nil {
				f7elem.Value = f7iter.Value
			}
			f7 = append(f7, *f7elem)
		}
		res.Tags = f7
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if len(r.ko.Spec.Targets) > 0 {
		if err = rm.syncTargets(
			ctx,
			r.ko.Spec.Name, r.ko.Spec.EventBusName,
			nil, r.ko.Spec.Targets,
		); err != nil {
			return nil, err
		}
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteRuleOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteRule(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteRule", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteRuleInput, error) {
	res := &svcsdk.DeleteRuleInput{}

	if r.ko.Spec.EventBusName != nil {
		res.EventBusName = r.ko.Spec.EventBusName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Rule,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidEventPatternException",
		"ManagedRuleException",
		"ValidationError",
		"ValidationException":
		return true
	default:
		return false
	}
}

// sdkTargetsFromResourceTargets converts the given Kubernetes resource targets to AWS service targets
func sdkTargetsFromResourceTargets(
	targets []*svcapitypes.Target,
) ([]*svcsdktypes.Target, error) {
	var res []*svcsdktypes.Target
	for _, krTarget := range targets {
		t := &svcsdktypes.Target{}
		if krTarget.ARN != nil {
			t.Arn = krTarget.ARN
		}
		if krTarget.BatchParameters != nil {
			tf1 := &svcsdktypes.BatchParameters{}
			if krTarget.BatchParameters.ArrayProperties != nil {
				tf1f0 := &svcsdktypes.BatchArrayProperties{}
				if krTarget.BatchParameters.ArrayProperties.Size != nil {
					sizeCopy0 := *krTarget.BatchParameters.ArrayProperties.Size
					if sizeCopy0 > math.MaxInt32 || sizeCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Size is of type int32")
					}
					sizeCopy := int32(sizeCopy0)
					tf1f0.Size = sizeCopy
				}
				tf1.ArrayProperties = tf1f0
			}
			if krTarget.BatchParameters.JobDefinition != nil {
				tf1.JobDefinition = krTarget.BatchParameters.JobDefinition
			}
			if krTarget.BatchParameters.JobName != nil {
				tf1.JobName = krTarget.BatchParameters.JobName
			}
			if krTarget.BatchParameters.RetryStrategy != nil {
				tf1f3 := &svcsdktypes.BatchRetryStrategy{}
				if krTarget.BatchParameters.RetryStrategy.Attempts != nil {
					attemptsCopy0 := *krTarget.BatchParameters.RetryStrategy.Attempts
					if attemptsCopy0 > math.MaxInt32 || attemptsCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Attempts is of type int32")
					}
					attemptsCopy := int32(attemptsCopy0)
					tf1f3.Attempts = attemptsCopy
				}
				tf1.RetryStrategy = tf1f3
			}
			t.BatchParameters = tf1
		}
		if krTarget.DeadLetterConfig != nil {
			tf2 := &svcsdktypes.DeadLetterConfig{}
			if krTarget.DeadLetterConfig.ARN != nil {
				tf2.Arn = krTarget.DeadLetterConfig.ARN
			}
			t.DeadLetterConfig = tf2
		}
		if krTarget.ECSParameters != nil {
			tf3 := &svcsdktypes.EcsParameters{}
			if krTarget.ECSParameters.CapacityProviderStrategy != nil {
				tf3f0 := []svcsdktypes.CapacityProviderStrategyItem{}
				for _, tf3f0iter := range krTarget.ECSParameters.CapacityProviderStrategy {
					tf3f0elem := &svcsdktypes.CapacityProviderStrategyItem{}
					if tf3f0iter.Base != nil {
						baseCopy0 := *tf3f0iter.Base
						if baseCopy0 > math.MaxInt32 || baseCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field base is of type int32")
						}
						baseCopy := int32(baseCopy0)
						tf3f0elem.Base = baseCopy
					}
					if tf3f0iter.CapacityProvider != nil {
						tf3f0elem.CapacityProvider = tf3f0iter.CapacityProvider
					}
					if tf3f0iter.Weight != nil {
						weightCopy0 := *tf3f0iter.Weight
						if weightCopy0 > math.MaxInt32 || weightCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field weight is of type int32")
						}
						weightCopy := int32(weightCopy0)
						tf3f0elem.Weight = weightCopy
					}
					tf3f0 = append(tf3f0, *tf3f0elem)
				}
				tf3.CapacityProviderStrategy = tf3f0
			}
			if krTarget.ECSParameters.EnableECSManagedTags != nil {
				tf3.EnableECSManagedTags = *krTarget.ECSParameters.EnableECSManagedTags
			}
			if krTarget.ECSParameters.EnableExecuteCommand != nil {
				tf3.EnableExecuteCommand = *krTarget.ECSParameters.EnableExecuteCommand
			}
			if krTarget.ECSParameters.Group != nil {
				tf3.Group = krTarget.ECSParameters.Group
			}
			if krTarget.ECSParameters.LaunchType != nil {
				tf3.LaunchType = svcsdktypes.LaunchType(*krTarget.ECSParameters.LaunchType)
			}
			if krTarget.ECSParameters.NetworkConfiguration != nil {
				tf3f5 := &svcsdktypes.NetworkConfiguration{}
				if krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration != nil {
					tf3f5f0 := &svcsdktypes.AwsVpcConfiguration{}
					if krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.AssignPublicIP != nil {
						tf3f5f0.AssignPublicIp = svcsdktypes.AssignPublicIp(*krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.AssignPublicIP)
					}
					if krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.SecurityGroups != nil {
						tf3f5f0.SecurityGroups = aws.ToStringSlice(krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.SecurityGroups)
					}
					if krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.Subnets != nil {
						tf3f5f0.Subnets = aws.ToStringSlice(krTarget.ECSParameters.NetworkConfiguration.AWSVPCConfiguration.Subnets)
					}
					tf3f5.AwsvpcConfiguration = tf3f5f0
				}
				tf3.NetworkConfiguration = tf3f5
			}
			if krTarget.ECSParameters.PlacementConstraints != nil {
				tf3f6 := []svcsdktypes.PlacementConstraint{}
				for _, tf3f6iter := range krTarget.ECSParameters.PlacementConstraints {
					tf3f6elem := &svcsdktypes.PlacementConstraint{}
					if tf3f6iter.Expression != nil {
						tf3f6elem.Expression = tf3f6iter.Expression
					}
					if tf3f6iter.Type != nil {
						tf3f6elem.Type = svcsdktypes.PlacementConstraintType(*tf3f6iter.Type)
					}
					tf3f6 = append(tf3f6, *tf3f6elem)
				}
				tf3.PlacementConstraints = tf3f6
			}
			if krTarget.ECSParameters.PlacementStrategy != nil {
				tf3f7 := []svcsdktypes.PlacementStrategy{}
				for _, tf3f7iter := range krTarget.ECSParameters.PlacementStrategy {
					tf3f7elem := &svcsdktypes.PlacementStrategy{}
					if tf3f7iter.Field != nil {
						tf3f7elem.Field = tf3f7iter.Field
					}
					if tf3f7iter.Type != nil {
						tf3f7elem.Type = svcsdktypes.PlacementStrategyType(*tf3f7iter.Type)
					}
					tf3f7 = append(tf3f7, *tf3f7elem)
				}
				tf3.PlacementStrategy = tf3f7
			}
			if krTarget.ECSParameters.PlatformVersion != nil {
				tf3.PlatformVersion = krTarget.ECSParameters.PlatformVersion
			}
			if krTarget.ECSParameters.PropagateTags != nil {
				tf3.PropagateTags = svcsdktypes.PropagateTags(*krTarget.ECSParameters.PropagateTags)
			}
			if krTarget.ECSParameters.ReferenceID != nil {
				tf3.ReferenceId = krTarget.ECSParameters.ReferenceID
			}
			if krTarget.ECSParameters.Tags != nil {
				tf3f11 := []svcsdktypes.Tag{}
				for _, tf3f11iter := range krTarget.ECSParameters.Tags {
					tf3f11elem := &svcsdktypes.Tag{}
					if tf3f11iter.Key != nil {
						tf3f11elem.Key = tf3f11iter.Key
					}
					if tf3f11iter.Value != nil {
						tf3f11elem.Value = tf3f11iter.Value
					}
					tf3f11 = append(tf3f11, *tf3f11elem)
				}
				tf3.Tags = tf3f11
			}
			if krTarget.ECSParameters.TaskCount != nil {
				taskCountCopy0 := *krTarget.ECSParameters.TaskCount
				if taskCountCopy0 > math.MaxInt32 || taskCountCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field TaskCount is of type int32")
				}
				taskCountCopy := int32(taskCountCopy0)
				tf3.TaskCount = &taskCountCopy
			}
			if krTarget.ECSParameters.TaskDefinitionARN != nil {
				tf3.TaskDefinitionArn = krTarget.ECSParameters.TaskDefinitionARN
			}
			t.EcsParameters = tf3
		}
		if krTarget.HTTPParameters != nil {
			tf4 := &svcsdktypes.HttpParameters{}
			if krTarget.HTTPParameters.HeaderParameters != nil {
				tf4.HeaderParameters = aws.ToStringMap(krTarget.HTTPParameters.HeaderParameters)
			}
			if krTarget.HTTPParameters.PathParameterValues != nil {
				tf4.PathParameterValues = aws.ToStringSlice(krTarget.HTTPParameters.PathParameterValues)
			}
			if krTarget.HTTPParameters.QueryStringParameters != nil {
				tf4.QueryStringParameters = aws.ToStringMap(krTarget.HTTPParameters.QueryStringParameters)
			}
			t.HttpParameters = tf4
		}
		if krTarget.ID != nil {
			t.Id = krTarget.ID
		}
		if krTarget.Input != nil {
			t.Input = krTarget.Input
		}
		if krTarget.InputPath != nil {
			t.InputPath = krTarget.InputPath
		}
		if krTarget.InputTransformer != nil {
			tf8 := &svcsdktypes.InputTransformer{}
			if krTarget.InputTransformer.InputPathsMap != nil {
				tf8.InputPathsMap = aws.ToStringMap(krTarget.InputTransformer.InputPathsMap)
			}
			if krTarget.InputTransformer.InputTemplate != nil {
				tf8.InputTemplate = krTarget.InputTransformer.InputTemplate
			}
			t.InputTransformer = tf8
		}
		if krTarget.KinesisParameters != nil {
			tf9 := &svcsdktypes.KinesisParameters{}
			if krTarget.KinesisParameters.PartitionKeyPath != nil {
				tf9.PartitionKeyPath = krTarget.KinesisParameters.PartitionKeyPath
			}
			t.KinesisParameters = tf9
		}
		if krTarget.RedshiftDataParameters != nil {
			tf10 := &svcsdktypes.RedshiftDataParameters{}
			if krTarget.RedshiftDataParameters.Database != nil {
				tf10.Database = krTarget.RedshiftDataParameters.Database
			}
			if krTarget.RedshiftDataParameters.DBUser != nil {
				tf10.DbUser = krTarget.RedshiftDataParameters.DBUser
			}
			if krTarget.RedshiftDataParameters.SecretManagerARN != nil {
				tf10.SecretManagerArn = krTarget.RedshiftDataParameters.SecretManagerARN
			}
			if krTarget.RedshiftDataParameters.SQL != nil {
				tf10.Sql = krTarget.RedshiftDataParameters.SQL
			}
			if krTarget.RedshiftDataParameters.SQLs != nil {
				tf10.Sqls = aws.ToStringSlice(krTarget.RedshiftDataParameters.SQLs)
			}
			if krTarget.RedshiftDataParameters.StatementName != nil {
				tf10.StatementName = krTarget.RedshiftDataParameters.StatementName
			}
			if krTarget.RedshiftDataParameters.WithEvent != nil {
				tf10.WithEvent = *krTarget.RedshiftDataParameters.WithEvent
			}
			t.RedshiftDataParameters = tf10
		}
		if krTarget.RetryPolicy != nil {
			tf11 := &svcsdktypes.RetryPolicy{}
			if krTarget.RetryPolicy.MaximumEventAgeInSeconds != nil {
				maximumEventAgeInSecondsCopy0 := *krTarget.RetryPolicy.MaximumEventAgeInSeconds
				if maximumEventAgeInSecondsCopy0 > math.MaxInt32 || maximumEventAgeInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MaximumEventAgeInSeconds is of type int32")
				}
				maximumEventAgeInSecondsCopy := int32(maximumEventAgeInSecondsCopy0)
				tf11.MaximumEventAgeInSeconds = &maximumEventAgeInSecondsCopy
			}
			if krTarget.RetryPolicy.MaximumRetryAttempts != nil {
				maximumRetryAttemptsCopy0 := *krTarget.RetryPolicy.MaximumRetryAttempts
				if maximumRetryAttemptsCopy0 > math.MaxInt32 || maximumRetryAttemptsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MaximumRetryAttempts is of type int32")
				}
				maximumRetryAttemptsCopy := int32(maximumRetryAttemptsCopy0)
				tf11.MaximumRetryAttempts = &maximumRetryAttemptsCopy
			}
			t.RetryPolicy = tf11
		}
		if krTarget.RoleARN != nil {
			t.RoleArn = krTarget.RoleARN
		}
		if krTarget.RunCommandParameters != nil {
			tf13 := &svcsdktypes.RunCommandParameters{}
			if krTarget.RunCommandParameters.RunCommandTargets != nil {
				tf13f0 := []svcsdktypes.RunCommandTarget{}
				for _, tf13f0iter := range krTarget.RunCommandParameters.RunCommandTargets {
					tf13f0elem := &svcsdktypes.RunCommandTarget{}
					if tf13f0iter.Key != nil {
						tf13f0elem.Key = tf13f0iter.Key
					}
					if tf13f0iter.Values != nil {
						tf13f0elem.Values = aws.ToStringSlice(tf13f0iter.Values)
					}
					tf13f0 = append(tf13f0, *tf13f0elem)
				}
				tf13.RunCommandTargets = tf13f0
			}
			t.RunCommandParameters = tf13
		}
		if krTarget.SageMakerPipelineParameters != nil {
			tf14 := &svcsdktypes.SageMakerPipelineParameters{}
			if krTarget.SageMakerPipelineParameters.PipelineParameterList != nil {
				tf14f0 := []svcsdktypes.SageMakerPipelineParameter{}
				for _, tf14f0iter := range krTarget.SageMakerPipelineParameters.PipelineParameterList {
					tf14f0elem := &svcsdktypes.SageMakerPipelineParameter{}
					if tf14f0iter.Name != nil {
						tf14f0elem.Name = tf14f0iter.Name
					}
					if tf14f0iter.Value != nil {
						tf14f0elem.Value = tf14f0iter.Value
					}
					tf14f0 = append(tf14f0, *tf14f0elem)
				}
				tf14.PipelineParameterList = tf14f0
			}
			t.SageMakerPipelineParameters = tf14
		}
		if krTarget.SQSParameters != nil {
			tf15 := &svcsdktypes.SqsParameters{}
			if krTarget.SQSParameters.MessageGroupID != nil {
				tf15.MessageGroupId = krTarget.SQSParameters.MessageGroupID
			}
			t.SqsParameters = tf15
		}

		res = append(res, t)
	}
	return res, nil
}

// resourceTargetsFromSDKTargets converts the given AWS service targets to Kubernetes resource targets
func resourceTargetsFromSDKTargets(
	targets []*svcsdktypes.Target,
) []*svcapitypes.Target {
	var res []*svcapitypes.Target
	for _, sdkTarget := range targets {
		t := &svcapitypes.Target{}
		// test
		if sdkTarget.Arn != nil {
			t.ARN = sdkTarget.Arn
		}
		if sdkTarget.BatchParameters != nil {
			tf1 := &svcapitypes.BatchParameters{}
			if sdkTarget.BatchParameters.ArrayProperties != nil {
				tf1f0 := &svcapitypes.BatchArrayProperties{}
				sizeCopy := int64(sdkTarget.BatchParameters.ArrayProperties.Size)
				tf1f0.Size = &sizeCopy
				tf1.ArrayProperties = tf1f0
			}
			if sdkTarget.BatchParameters.JobDefinition != nil {
				tf1.JobDefinition = sdkTarget.BatchParameters.JobDefinition
			}
			if sdkTarget.BatchParameters.JobName != nil {
				tf1.JobName = sdkTarget.BatchParameters.JobName
			}
			if sdkTarget.BatchParameters.RetryStrategy != nil {
				tf1f3 := &svcapitypes.BatchRetryStrategy{}
				attemptsCopy := int64(sdkTarget.BatchParameters.RetryStrategy.Attempts)
				tf1f3.Attempts = &attemptsCopy
				tf1.RetryStrategy = tf1f3
			}
			t.BatchParameters = tf1
		}
		if sdkTarget.DeadLetterConfig != nil {
			tf2 := &svcapitypes.DeadLetterConfig{}
			if sdkTarget.DeadLetterConfig.Arn != nil {
				tf2.ARN = sdkTarget.DeadLetterConfig.Arn
			}
			t.DeadLetterConfig = tf2
		}
		if sdkTarget.EcsParameters != nil {
			tf3 := &svcapitypes.ECSParameters{}
			if sdkTarget.EcsParameters.CapacityProviderStrategy != nil {
				tf3f0 := []*svcapitypes.CapacityProviderStrategyItem{}
				for _, tf3f0iter := range sdkTarget.EcsParameters.CapacityProviderStrategy {
					tf3f0elem := &svcapitypes.CapacityProviderStrategyItem{}
					baseCopy := int64(tf3f0iter.Base)
					tf3f0elem.Base = &baseCopy
					if tf3f0iter.CapacityProvider != nil {
						tf3f0elem.CapacityProvider = tf3f0iter.CapacityProvider
					}
					weightCopy := int64(tf3f0iter.Weight)
					tf3f0elem.Weight = &weightCopy
					tf3f0 = append(tf3f0, tf3f0elem)
				}
				tf3.CapacityProviderStrategy = tf3f0
			}
			tf3.EnableECSManagedTags = &sdkTarget.EcsParameters.EnableECSManagedTags
			tf3.EnableExecuteCommand = &sdkTarget.EcsParameters.EnableExecuteCommand
			if sdkTarget.EcsParameters.Group != nil {
				tf3.Group = sdkTarget.EcsParameters.Group
			}
			if sdkTarget.EcsParameters.LaunchType != "" {
				tf3.LaunchType = aws.String(string(sdkTarget.EcsParameters.LaunchType))
			}
			if sdkTarget.EcsParameters.NetworkConfiguration != nil {
				tf3f5 := &svcapitypes.NetworkConfiguration{}
				if sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration != nil {
					tf3f5f0 := &svcapitypes.AWSVPCConfiguration{}
					if sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.AssignPublicIp != "" {
						tf3f5f0.AssignPublicIP = aws.String(string(sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.AssignPublicIp))
					}
					if sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.SecurityGroups != nil {
						tf3f5f0.SecurityGroups = aws.StringSlice(sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.SecurityGroups)
					}
					if sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.Subnets != nil {
						tf3f5f0.Subnets = aws.StringSlice(sdkTarget.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.Subnets)
					}
					tf3f5.AWSVPCConfiguration = tf3f5f0
				}
				tf3.NetworkConfiguration = tf3f5
			}
			if sdkTarget.EcsParameters.PlacementConstraints != nil {
				tf3f6 := []*svcapitypes.PlacementConstraint{}
				for _, tf3f6iter := range sdkTarget.EcsParameters.PlacementConstraints {
					tf3f6elem := &svcapitypes.PlacementConstraint{}
					if tf3f6iter.Expression != nil {
						tf3f6elem.Expression = tf3f6iter.Expression
					}
					if tf3f6iter.Type != "" {
						tf3f6elem.Type = aws.String(string(tf3f6iter.Type))
					}
					tf3f6 = append(tf3f6, tf3f6elem)
				}
				tf3.PlacementConstraints = tf3f6
			}
			if sdkTarget.EcsParameters.PlacementStrategy != nil {
				tf3f7 := []*svcapitypes.PlacementStrategy{}
				for _, tf3f7iter := range sdkTarget.EcsParameters.PlacementStrategy {
					tf3f7elem := &svcapitypes.PlacementStrategy{}
					if tf3f7iter.Field != nil {
						tf3f7elem.Field = tf3f7iter.Field
					}
					if tf3f7iter.Type != "" {
						tf3f7elem.Type = aws.String(string(tf3f7iter.Type))
					}
					tf3f7 = append(tf3f7, tf3f7elem)
				}
				tf3.PlacementStrategy = tf3f7
			}
			if sdkTarget.EcsParameters.PlatformVersion != nil {
				tf3.PlatformVersion = sdkTarget.EcsParameters.PlatformVersion
			}
			if sdkTarget.EcsParameters.PropagateTags != "" {
				tf3.PropagateTags = aws.String(string(sdkTarget.EcsParameters.PropagateTags))
			}
			if sdkTarget.EcsParameters.ReferenceId != nil {
				tf3.ReferenceID = sdkTarget.EcsParameters.ReferenceId
			}
			if sdkTarget.EcsParameters.Tags != nil {
				tf3f11 := []*svcapitypes.Tag{}
				for _, tf3f11iter := range sdkTarget.EcsParameters.Tags {
					tf3f11elem := &svcapitypes.Tag{}
					if tf3f11iter.Key != nil {
						tf3f11elem.Key = tf3f11iter.Key
					}
					if tf3f11iter.Value != nil {
						tf3f11elem.Value = tf3f11iter.Value
					}
					tf3f11 = append(tf3f11, tf3f11elem)
				}
				tf3.Tags = tf3f11
			}
			if sdkTarget.EcsParameters.TaskCount != nil {
				taskCountCopy := int64(*sdkTarget.EcsParameters.TaskCount)
				tf3.TaskCount = &taskCountCopy
			}
			if sdkTarget.EcsParameters.TaskDefinitionArn != nil {
				tf3.TaskDefinitionARN = sdkTarget.EcsParameters.TaskDefinitionArn
			}
			t.ECSParameters = tf3
		}
		if sdkTarget.HttpParameters != nil {
			tf4 := &svcapitypes.HTTPParameters{}
			if sdkTarget.HttpParameters.HeaderParameters != nil {
				tf4.HeaderParameters = aws.StringMap(sdkTarget.HttpParameters.HeaderParameters)
			}
			if sdkTarget.HttpParameters.PathParameterValues != nil {
				tf4.PathParameterValues = aws.StringSlice(sdkTarget.HttpParameters.PathParameterValues)
			}
			if sdkTarget.HttpParameters.QueryStringParameters != nil {
				tf4.QueryStringParameters = aws.StringMap(sdkTarget.HttpParameters.QueryStringParameters)
			}
			t.HTTPParameters = tf4
		}
		if sdkTarget.Id != nil {
			t.ID = sdkTarget.Id
		}
		if sdkTarget.Input != nil {
			t.Input = sdkTarget.Input
		}
		if sdkTarget.InputPath != nil {
			t.InputPath = sdkTarget.InputPath
		}
		if sdkTarget.InputTransformer != nil {
			tf8 := &svcapitypes.InputTransformer{}
			if sdkTarget.InputTransformer.InputPathsMap != nil {
				tf8.InputPathsMap = aws.StringMap(sdkTarget.InputTransformer.InputPathsMap)
			}
			if sdkTarget.InputTransformer.InputTemplate != nil {
				tf8.InputTemplate = sdkTarget.InputTransformer.InputTemplate
			}
			t.InputTransformer = tf8
		}
		if sdkTarget.KinesisParameters != nil {
			tf9 := &svcapitypes.KinesisParameters{}
			if sdkTarget.KinesisParameters.PartitionKeyPath != nil {
				tf9.PartitionKeyPath = sdkTarget.KinesisParameters.PartitionKeyPath
			}
			t.KinesisParameters = tf9
		}
		if sdkTarget.RedshiftDataParameters != nil {
			tf10 := &svcapitypes.RedshiftDataParameters{}
			if sdkTarget.RedshiftDataParameters.Database != nil {
				tf10.Database = sdkTarget.RedshiftDataParameters.Database
			}
			if sdkTarget.RedshiftDataParameters.DbUser != nil {
				tf10.DBUser = sdkTarget.RedshiftDataParameters.DbUser
			}
			if sdkTarget.RedshiftDataParameters.SecretManagerArn != nil {
				tf10.SecretManagerARN = sdkTarget.RedshiftDataParameters.SecretManagerArn
			}
			if sdkTarget.RedshiftDataParameters.Sql != nil {
				tf10.SQL = sdkTarget.RedshiftDataParameters.Sql
			}
			if sdkTarget.RedshiftDataParameters.Sqls != nil {
				tf10.SQLs = aws.StringSlice(sdkTarget.RedshiftDataParameters.Sqls)
			}
			if sdkTarget.RedshiftDataParameters.StatementName != nil {
				tf10.StatementName = sdkTarget.RedshiftDataParameters.StatementName
			}
			tf10.WithEvent = &sdkTarget.RedshiftDataParameters.WithEvent
			t.RedshiftDataParameters = tf10
		}
		if sdkTarget.RetryPolicy != nil {
			tf11 := &svcapitypes.RetryPolicy{}
			if sdkTarget.RetryPolicy.MaximumEventAgeInSeconds != nil {
				maximumEventAgeInSecondsCopy := int64(*sdkTarget.RetryPolicy.MaximumEventAgeInSeconds)
				tf11.MaximumEventAgeInSeconds = &maximumEventAgeInSecondsCopy
			}
			if sdkTarget.RetryPolicy.MaximumRetryAttempts != nil {
				maximumRetryAttemptsCopy := int64(*sdkTarget.RetryPolicy.MaximumRetryAttempts)
				tf11.MaximumRetryAttempts = &maximumRetryAttemptsCopy
			}
			t.RetryPolicy = tf11
		}
		if sdkTarget.RoleArn != nil {
			t.RoleARN = sdkTarget.RoleArn
		}
		if sdkTarget.RunCommandParameters != nil {
			tf13 := &svcapitypes.RunCommandParameters{}
			if sdkTarget.RunCommandParameters.RunCommandTargets != nil {
				tf13f0 := []*svcapitypes.RunCommandTarget{}
				for _, tf13f0iter := range sdkTarget.RunCommandParameters.RunCommandTargets {
					tf13f0elem := &svcapitypes.RunCommandTarget{}
					if tf13f0iter.Key != nil {
						tf13f0elem.Key = tf13f0iter.Key
					}
					if tf13f0iter.Values != nil {
						tf13f0elem.Values = aws.StringSlice(tf13f0iter.Values)
					}
					tf13f0 = append(tf13f0, tf13f0elem)
				}
				tf13.RunCommandTargets = tf13f0
			}
			t.RunCommandParameters = tf13
		}
		if sdkTarget.SageMakerPipelineParameters != nil {
			tf14 := &svcapitypes.SageMakerPipelineParameters{}
			if sdkTarget.SageMakerPipelineParameters.PipelineParameterList != nil {
				tf14f0 := []*svcapitypes.SageMakerPipelineParameter{}
				for _, tf14f0iter := range sdkTarget.SageMakerPipelineParameters.PipelineParameterList {
					tf14f0elem := &svcapitypes.SageMakerPipelineParameter{}
					if tf14f0iter.Name != nil {
						tf14f0elem.Name = tf14f0iter.Name
					}
					if tf14f0iter.Value != nil {
						tf14f0elem.Value = tf14f0iter.Value
					}
					tf14f0 = append(tf14f0, tf14f0elem)
				}
				tf14.PipelineParameterList = tf14f0
			}
			t.SageMakerPipelineParameters = tf14
		}
		if sdkTarget.SqsParameters != nil {
			tf15 := &svcapitypes.SQSParameters{}
			if sdkTarget.SqsParameters.MessageGroupId != nil {
				tf15.MessageGroupID = sdkTarget.SqsParameters.MessageGroupId
			}
			t.SQSParameters = tf15
		}

		res = append(res, t)
	}
	return res
}
