// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type APIDestinationHTTPMethod string

const (
	APIDestinationHTTPMethod_DELETE  APIDestinationHTTPMethod = "DELETE"
	APIDestinationHTTPMethod_GET     APIDestinationHTTPMethod = "GET"
	APIDestinationHTTPMethod_HEAD    APIDestinationHTTPMethod = "HEAD"
	APIDestinationHTTPMethod_OPTIONS APIDestinationHTTPMethod = "OPTIONS"
	APIDestinationHTTPMethod_PATCH   APIDestinationHTTPMethod = "PATCH"
	APIDestinationHTTPMethod_POST    APIDestinationHTTPMethod = "POST"
	APIDestinationHTTPMethod_PUT     APIDestinationHTTPMethod = "PUT"
)

type APIDestinationState string

const (
	APIDestinationState_ACTIVE   APIDestinationState = "ACTIVE"
	APIDestinationState_INACTIVE APIDestinationState = "INACTIVE"
)

type ArchiveState string

const (
	ArchiveState_CREATE_FAILED ArchiveState = "CREATE_FAILED"
	ArchiveState_CREATING      ArchiveState = "CREATING"
	ArchiveState_DISABLED      ArchiveState = "DISABLED"
	ArchiveState_ENABLED       ArchiveState = "ENABLED"
	ArchiveState_UPDATE_FAILED ArchiveState = "UPDATE_FAILED"
	ArchiveState_UPDATING      ArchiveState = "UPDATING"
)

type AssignPublicIP string

const (
	AssignPublicIP_DISABLED AssignPublicIP = "DISABLED"
	AssignPublicIP_ENABLED  AssignPublicIP = "ENABLED"
)

type ConnectionAuthorizationType string

const (
	ConnectionAuthorizationType_API_KEY                  ConnectionAuthorizationType = "API_KEY"
	ConnectionAuthorizationType_BASIC                    ConnectionAuthorizationType = "BASIC"
	ConnectionAuthorizationType_OAUTH_CLIENT_CREDENTIALS ConnectionAuthorizationType = "OAUTH_CLIENT_CREDENTIALS"
)

type ConnectionOAuthHTTPMethod string

const (
	ConnectionOAuthHTTPMethod_GET  ConnectionOAuthHTTPMethod = "GET"
	ConnectionOAuthHTTPMethod_POST ConnectionOAuthHTTPMethod = "POST"
	ConnectionOAuthHTTPMethod_PUT  ConnectionOAuthHTTPMethod = "PUT"
)

type ConnectionState string

const (
	ConnectionState_ACTIVE              ConnectionState = "ACTIVE"
	ConnectionState_AUTHORIZED          ConnectionState = "AUTHORIZED"
	ConnectionState_AUTHORIZING         ConnectionState = "AUTHORIZING"
	ConnectionState_CREATING            ConnectionState = "CREATING"
	ConnectionState_DEAUTHORIZED        ConnectionState = "DEAUTHORIZED"
	ConnectionState_DEAUTHORIZING       ConnectionState = "DEAUTHORIZING"
	ConnectionState_DELETING            ConnectionState = "DELETING"
	ConnectionState_FAILED_CONNECTIVITY ConnectionState = "FAILED_CONNECTIVITY"
	ConnectionState_UPDATING            ConnectionState = "UPDATING"
)

type EndpointState string

const (
	EndpointState_ACTIVE        EndpointState = "ACTIVE"
	EndpointState_CREATE_FAILED EndpointState = "CREATE_FAILED"
	EndpointState_CREATING      EndpointState = "CREATING"
	EndpointState_DELETE_FAILED EndpointState = "DELETE_FAILED"
	EndpointState_DELETING      EndpointState = "DELETING"
	EndpointState_UPDATE_FAILED EndpointState = "UPDATE_FAILED"
	EndpointState_UPDATING      EndpointState = "UPDATING"
)

type EventSourceState string

const (
	EventSourceState_ACTIVE  EventSourceState = "ACTIVE"
	EventSourceState_DELETED EventSourceState = "DELETED"
	EventSourceState_PENDING EventSourceState = "PENDING"
)

type LaunchType string

const (
	LaunchType_EC2      LaunchType = "EC2"
	LaunchType_EXTERNAL LaunchType = "EXTERNAL"
	LaunchType_FARGATE  LaunchType = "FARGATE"
)

type PlacementConstraintType string

const (
	PlacementConstraintType_distinctInstance PlacementConstraintType = "distinctInstance"
	PlacementConstraintType_memberOf         PlacementConstraintType = "memberOf"
)

type PlacementStrategyType string

const (
	PlacementStrategyType_binpack PlacementStrategyType = "binpack"
	PlacementStrategyType_random  PlacementStrategyType = "random"
	PlacementStrategyType_spread  PlacementStrategyType = "spread"
)

type PropagateTags string

const (
	PropagateTags_TASK_DEFINITION PropagateTags = "TASK_DEFINITION"
)

type ReplayState string

const (
	ReplayState_CANCELLED  ReplayState = "CANCELLED"
	ReplayState_CANCELLING ReplayState = "CANCELLING"
	ReplayState_COMPLETED  ReplayState = "COMPLETED"
	ReplayState_FAILED     ReplayState = "FAILED"
	ReplayState_RUNNING    ReplayState = "RUNNING"
	ReplayState_STARTING   ReplayState = "STARTING"
)

type ReplicationState string

const (
	ReplicationState_DISABLED ReplicationState = "DISABLED"
	ReplicationState_ENABLED  ReplicationState = "ENABLED"
)

type RuleState string

const (
	RuleState_DISABLED                                      RuleState = "DISABLED"
	RuleState_ENABLED                                       RuleState = "ENABLED"
	RuleState_ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS RuleState = "ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS"
)
